crud/config/routes.rb
Rails.application.routes.draw do
  mount ForestLiana::Engine => '/forest'
  devise_for :users
  resources :books
  # root 'books#index'
  root 'home#main'
  get 'home/main'
  get 'counsel', to:'counsel#index'
end

crud/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

crud/app/models/book.rb
class Book < ApplicationRecord
    # has_secure_password
    validates :address,:contact_number,:age,:email, presence: true
    validates :contact_number,length: { in: 8..10 }
    belongs_to :user
end

crud/app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :book
end

crud/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        books_path
    end
end

crud/app/controllers/books_controller.rb
class BooksController < ApplicationController
  before_action :set_book, only: %i[ show edit update destroy ]
  before_action :authenticate_user!, except: [:index, :show]
  before_action :correct_user, only: [:edit, :destroy]
  # GET /books or /books.json
  def index
    @books = Book.all
  end

  # GET /books/1 or /books/1.json
  def show
    # render plain: params[:id]
  end

  # GET /books/new
  def new
    # @book = Book.new
    @book=current_user.book.build
  end

  # GET /books/1/edit
  def edit
  end

  # POST /books or /books.json
  def create
    # @book = Book.new(book_params)
    @book=current_user.book.build(book_params)
    respond_to do |format|
      if @book.save
        format.html { redirect_to @book, notice: "Appointment is successfully booked." }
        format.json { render :show, status: :created, location: @book }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /books/1 or /books/1.json
  def update
    respond_to do |format|
      if @book.update(book_params)
        format.html { redirect_to @book, notice: "Appointment is successfully updated." }
        format.json { render :show, status: :ok, location: @book }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @book.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /books/1 or /books/1.json
  def destroy
    @book.destroy
    respond_to do |format|
      format.html { redirect_to books_url, notice: "Appointment is successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def correct_user
    @book = current_user.book.find_by(id: params[:id])
    redirect_to books_path, notice: "Not Authorised" if @book.nil?
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_book
      @book = Book.find(params[:id])
    end




    # Only allow a list of trusted parameters through.
    def book_params
      params.require(:book).permit(:name, :address, :age,:email,:user_id,:contact_number,:date)
    end
end

crud/app/controllers/counsel_controller.rb
class CounselController < ApplicationController
  def index; end
end

crud/app/controllers/home_controller.rb
class HomeController < ApplicationController
    def index
        puts params[:name]
    end
end

crud/app/helpers/application_helper.rb
module ApplicationHelper
end

crud/app/helpers/books_helper.rb
module BooksHelper
end

crud/app/views/books/_form.html.erb
<%= form_with(model: book) do |form| %>
  <% if book.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(book.errors.count, "error") %> prohibited this book from being saved:</h2>

      <ul>
        <% book.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <div class="container img">
<div class="row">
<div class="col-6 mx-auto border border-2 border-primary rounded wrap">

<table  class='table' >

  <div class="field form-group input-container">
    <i class="fa fa-user icon"></i>
    <%= form.label :name %>
    <%= form.text_field :name, class:"form-control border-info input-field" %>
  </div>
   <br>
  <div class="field form-group">
    <i class="glyphicon glyphicon-home"></i>
    <%= form.label :address %>
    <%= form.text_field :address,class:"form-control border-info " %>
  </div>
<br>
  <div class="field form-group">
     <i class="fa fa-phone" aria-hidden="true"></i>
     <%= form.label :contact_number %>
    <%= form.number_field :contact_number,class:"form-control border-info" %>
  </div>
<br>
<br>
  <div class="field form-group">
    <i class="fa fa-id-badge" style="font-size:20px"></i>
    <%= form.label :age %>
    <%= form.number_field :age,class:"form-control border-info" %>
  </div>
<br>
<br>
  <div class="field form-group">
  <i class="fa fa-envelope icon"></i>
    <%= form.label :email %>
    <%= form.text_field :email,class:"form-control border-info" %>
  </div>
<br>
<div class="field">
<i class='far fa-calendar-alt' style='font-size:24px'></i>
<%= form.label :date %>
<%= form.date_select :date%>
</div>


<br>
  <div class="field form-group ">
    <%= form.number_field :user_id , id: :friend_user_id, class:"form-control",value:current_user.id,type: :hidden %>
  </div>
  
<br>
  <div class="actions ">
    <%= form.submit 'Book Appointment ',class:"btn btn-outline-primary"%>
  </div>
  </table>
  </div>
  </div>
  </div>
<% end %>

crud/app/views/books/edit.html.erb
<h1>Editing Book</h1>

<%= render 'form', book: @book %>

<%= link_to 'Show', @book %> |
<%= link_to 'Back', books_path %>

crud/app/views/books/index.html.erb
<p id="notice"><%= notice %></p>
<div class='bkg' >
<h1>Users</h1>
<table  class='table table-hover' >
  <thead class="thead-dark" >
    <tr>
      <th>Name</th>
      <th>Address</th>
      <th>Contact Number</th>
      <th>Age</th>
      <th>Email</th>
      <th>Appointment Date</th>
      <th>Status</th>
      
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody  >
    <% @books.each do |book| %>
      <tr>
        <td><%= link_to book.name, book, class:'name' %></td>
        <td><%= book.address %></td>
        <td><%= book.contact_number %></td>
        <td><%= book.age %></td>
        <td><%= book.email %></td>
        <td><%= book.date %></td>
        <td><%= book.status %></td>
        
<%# <button type="button" class="btn btn-danger">Danger</button> %>
        <td><%= link_to 'Edit', edit_book_path(book),class:"btn btn-outline-primary" %></td>
        <td><%= link_to 'Destroy', book, class:"btn btn-outline-danger",method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'Book Appointment', new_book_path, class:"btn btn-outline-success"  %>

</div>

crud/app/views/books/new.html.erb
<div class="text-center">
<h1> User's Details</h1>
</div>
<%= render 'form', book: @book %>

<%= link_to 'Back', books_path,class:"btn btn-secondary" %>

crud/app/views/books/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @book.name %>
</p>

<p>
  <strong>Address:</strong>
  <%= @book.address %>
</p>

<p>
  <strong>Contact number:</strong>
  <%= @book.contact_number %>
</p>

<p>
  <strong>Age:</strong>
  <%= @book.age %>
</p>

<p>
  <strong>Email:</strong>
  <%= @book.email %>
</p>
<p>
  <strong>Date:</strong>
  <%= @book.date %>
</p>

<%= link_to 'Edit', edit_book_path(@book) %> |
<%= link_to 'Back', books_path %>

crud/app/views/home/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light navbar-dark bg-dark">
    <div class="container-fluid">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
        aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav ml-auto mb-2 mb-lg-0">
          <li class="nav-item">
          <%= link_to "Home", home_main_path, class:"nav-link active" %>
          </li>
           <li class="nav-item">
          <%= link_to "Book Appointment", books_path, class:"nav-link active" %>
          </li>
          <% if user_signed_in? %>
          <li class="nav-item">
          <%= link_to "Sign out", destroy_user_session_path,method: :delete, class:"nav-link " %>
          </li>
          <li class="nav-item">
          <%= link_to "Modify", edit_user_registration_path, class:"nav-link " %>
          </li>
          
           <%else%>
          <li class="nav-item">
             <%= link_to "Sign up",  new_user_registration_path, class:"nav-link " %>
          </li>
          <li class="nav-item">
             <%= link_to "Sign In", new_user_session_path, class:"nav-link " %>
          </li>
          <%end%>
        </ul>
      </div>
      
    </div>
  </nav>

crud/app/views/home/index.html.erb
<h1>Home index</h1>

crud/app/views/home/main.html.erb
  
  <div id="carouselExampleDark" class="carousel slide," data-bs-ride="carousel">
    <div class="carousel-indicators">
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="0" class="active"
        aria-current="true" aria-label="Slide 1"></button>
      <button type="button" data-bs-target="#carouselExampleDark" data-bs-slide-to="1" aria-label="Slide 2"></button>
     
    </div>
    
    <div class="carousel-inner container ">
      <div class="carousel-item active " data-bs-interval="10000">
        <img src="https://canadianschoolcounsellor.com/wp-content/uploads/2019/03/CounsellorsCorner-990x688.jpg" class=" image d-block w-100 " alt="...">
      </div>
      <div class="carousel-item" data-bs-interval="2000">
        <img src="https://online.grace.edu/wp-content/uploads/2020/05/4-Popular-Mental-Health-Counseling-Theories-from-Grace-College-1024x576.png" class="image d-block w-100" alt="...">
        <div class="carousel-caption d-none d-md-block">


        </div>
      </div>
      
    </div>
    <button class="carousel-control-prev" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="prev">
      <span class="carousel-control-prev-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Previous</span>
    </button>
    <button class="carousel-control-next" type="button" data-bs-target="#carouselExampleDark" data-bs-slide="next">
      <span class="carousel-control-next-icon" aria-hidden="true"></span>
      <span class="visually-hidden">Next</span>
    </button>
  </div>
  <section class="main my-5 ">
    <div class="text-center">
      <h1 id="about-us">About Us</h1>
      <hr class="w-25 mx-auto" />
      <div class="container">
        <div class="row">
          <div class="col-lg-6 col-md-6 col-12 col-xxl-6 d-flex justify-content-center align-items-start flex-column">
            <figure>
              <img src="https://www.training.com.au/wp-content/uploads/counsellordayinthelife_Feature.png" class="img-fluid" alt="">
            </figure>
          </div>
          <div class="col-lg-6 col-md-6 col-12 col-xxl-6">
            <h1>Who WE ARE</h1>
            <p>Our online counselors are Masters in Psychology and go through extensive rounds of assessment before coming onboard. We map their efficacy with the help of constant feedback from the clients, peers, and domain experts.
            This keeps the quality of BetterLyf sessions thriving.Your counsellor spends hours reflecting and researching methods and tools in addition to your sessions in order to assist you with the best possible tactics to deal with complex situations.
              </p>
          </div>
        </div>
      </div>
    </div>
  </section>

crud/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Present</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  <%= render partial: 'home/navbar'%>
  <p class="alert"><%= alert %></p>
    <%= yield %>
    
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.6.0/dist/umd/popper.min.js"
            integrity="sha384-KsvD1yqQ1/1+IA7gi3P0tyJcT3vR+NdBTt13hSJ2lnve8agRGXTTyNaBYmCR/Nwi"
            crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta2/dist/js/bootstrap.min.js"
            integrity="sha384-nsg8ua9HAw1y0W1btsyWgBklPnCUAFLuTMS2G72MMONqmOymq585AcH49TLBQObG"
            crossorigin="anonymous"></script>
  </body>
</html>